export const REGION_ORDER = [
  "Atlantic",
  "South",
  "Central",
  "Southeast",
  "East",
  "South Central",
  "Midwest",
  "West",
];

export const BRACKET = {
  title: "2026 NCAA Division II Men's Basketball Championship",
  regions: [
    {
      name: "Atlantic",
      teams: [
        { seed: 1, name: "Gannon", record: "28-3" },
        { seed: 8, name: "Charleston (WV)", record: "19-9" },
        { seed: 4, name: "California (PA)", record: "22-8" },
        { seed: 5, name: "Fayetteville St.", record: "23-6" },
        { seed: 2, name: "West Liberty", record: "27-4" },
        { seed: 7, name: "Virginia Union", record: "24-5" },
        { seed: 3, name: "Fairmont St.", record: "26-5" },
        { seed: 6, name: "Indiana (PA)", record: "22-7" },
      ],
    },
    {
      name: "South",
      teams: [
        { seed: 1, name: "Nova Southeastern", record: "27-1" },
        { seed: 8, name: "Morehouse", record: "22-9" },
        { seed: 4, name: "Fla. Southern", record: "22-10" },
        { seed: 5, name: "Montevallo", record: "21-8" },
        { seed: 2, name: "Palm Beach Atl.", record: "26-5" },
        { seed: 7, name: "UAH", record: "21-9" },
        { seed: 3, name: "West Ala.", record: "26-5" },
        { seed: 6, name: "West Florida", record: "25-8" },
      ],
    },
    {
      name: "Central",
      teams: [
        { seed: 1, name: "Washburn", record: "31-1" },
        { seed: 8, name: "Minn. Duluth", record: "21-11" },
        { seed: 4, name: "St. Cloud St.", record: "25-6" },
        { seed: 5, name: "Missouri Western", record: "21-11" },
        { seed: 2, name: "Okla. Baptist", record: "27-3" },
        { seed: 7, name: "Harding", record: "24-7" },
        { seed: 3, name: "Central Mo.", record: "23-9" },
        { seed: 6, name: "Rogers St.", record: "21-10" },
      ],
    },
    {
      name: "Southeast",
      teams: [
        { seed: 1, name: "Anderson (SC)", record: "29-2" },
        { seed: 8, name: "Young Harris", record: "22-8" },
        { seed: 4, name: "Lenoir-Rhyne", record: "24-8" },
        { seed: 5, name: "North Georgia", record: "22-7" },
        { seed: 2, name: "Lander", record: "25-5" },
        { seed: 7, name: "Lincoln Memorial", record: "19-11" },
        { seed: 3, name: "Catawba", record: "23-8" },
        { seed: 6, name: "Columbus St.", record: "22-8" },
      ],
    },
    {
      name: "East",
      teams: [
        { seed: 1, name: "Daemen", record: "30-1" },
        { seed: 8, name: "Goldey-Beacom", record: "21-10" },
        { seed: 4, name: "Bentley", record: "19-9" },
        { seed: 5, name: "Saint Michael's", record: "18-13" },
        { seed: 2, name: "Felician", record: "27-3" },
        { seed: 7, name: "Adelphi", record: "18-11" },
        { seed: 3, name: "Saint Anselm", record: "23-7" },
        { seed: 6, name: "Assumption", record: "17-12" },
      ],
    },
    {
      name: "South Central",
      teams: [
        { seed: 1, name: "DBU", record: "27-6" },
        { seed: 8, name: "Colorado Mesa", record: "21-10" },
        { seed: 4, name: "Western N.M.", record: "22-7" },
        { seed: 5, name: "St. Edward's", record: "24-8" },
        { seed: 2, name: "Eastern N.M.", record: "26-5" },
        { seed: 7, name: "St. Mary's (TX)", record: "21-9" },
        { seed: 3, name: "Lubbock Christian", record: "27-5" },
        { seed: 6, name: "Black Hills St.", record: "27-4" },
      ],
    },
    {
      name: "Midwest",
      teams: [
        { seed: 1, name: "Walsh", record: "27-3" },
        { seed: 8, name: "William Jewell", record: "22-9" },
        { seed: 4, name: "Rockhurst", record: "23-6" },
        { seed: 5, name: "Northern Mich.", record: "27-6" },
        { seed: 2, name: "Grand Valley St.", record: "25-6" },
        { seed: 7, name: "Ashland", record: "20-10" },
        { seed: 3, name: "Michigan Tech", record: "26-6" },
        { seed: 6, name: "Lake Erie", record: "23-8" },
      ],
    },
    {
      name: "West",
      teams: [
        { seed: 1, name: "Cal St. East Bay", record: "30-0" },
        { seed: 8, name: "Cal Poly Humboldt", record: "17-14" },
        { seed: 4, name: "Alas. Anchorage", record: "21-10" },
        { seed: 5, name: "Cal St. Dom. Hills", record: "22-8" },
        { seed: 2, name: "Saint Martin's", record: "25-5" },
        { seed: 7, name: "Hawaii Pacific", record: "18-11" },
        { seed: 3, name: "Point Loma", record: "25-5" },
        { seed: 6, name: "Northwest Nazarene", record: "18-10" },
      ],
    },
  ],
};